-- MySQL Script generated by MySQL Workbench
-- Wed Aug 11 14:27:45 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema JbikeDH
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema JbikeDH
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `JbikeDH` DEFAULT CHARACTER SET utf8 ;
USE `JbikeDH` ;

-- -----------------------------------------------------
-- Table `JbikeDH`.`addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JbikeDH`.`addresses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(45) NULL,
  `number` VARCHAR(45) NULL,
  `apt` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `zipcode` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JbikeDH`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JbikeDH`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JbikeDH`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JbikeDH`.`genre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JbikeDH`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JbikeDH`.`users` (
  `id` INT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `addresses_id` INT NOT NULL,
  `roles_id` INT NOT NULL,
  `genre_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_addresses_idx` (`addresses_id` ASC) VISIBLE,
  INDEX `fk_users_roles1_idx` (`roles_id` ASC) VISIBLE,
  INDEX `fk_users_genre1_idx` (`genre_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_addresses`
    FOREIGN KEY (`addresses_id`)
    REFERENCES `JbikeDH`.`addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_roles1`
    FOREIGN KEY (`roles_id`)
    REFERENCES `JbikeDH`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_genre1`
    FOREIGN KEY (`genre_id`)
    REFERENCES `JbikeDH`.`genre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JbikeDH`.`brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JbikeDH`.`brands` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JbikeDH`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JbikeDH`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(45) NULL,
  `desc1` TEXT NULL,
  `desc2` TEXT NULL,
  `image1` VARCHAR(225) NULL,
  `image2` VARCHAR(225) NULL,
  `image3` VARCHAR(225) NULL,
  `image4` VARCHAR(225) NULL,
  `keywords` TEXT NULL,
  `stock` INT(10) NULL,
  `price` DECIMAL NULL,
  `discount` INT NULL,
  `cuotas` INT NULL,
  `productscol` VARCHAR(45) NULL,
  `brands_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_products_brands1_idx` (`brands_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_brands1`
    FOREIGN KEY (`brands_id`)
    REFERENCES `JbikeDH`.`brands` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JbikeDH`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JbikeDH`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JbikeDH`.`categoryproducts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JbikeDH`.`categoryproducts` (
  `products_id` INT NOT NULL,
  `categories_id` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_products_has_categories_categories1_idx` (`categories_id` ASC) VISIBLE,
  INDEX `fk_products_has_categories_products1_idx` (`products_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_products_has_categories_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `JbikeDH`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_has_categories_categories1`
    FOREIGN KEY (`categories_id`)
    REFERENCES `JbikeDH`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JbikeDH`.`sizes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JbikeDH`.`sizes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `size` DOUBLE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JbikeDH`.`sizeproducts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JbikeDH`.`sizeproducts` (
  `products_id` INT NOT NULL,
  `sizes_id` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_products_has_sizes_sizes1_idx` (`sizes_id` ASC) VISIBLE,
  INDEX `fk_products_has_sizes_products1_idx` (`products_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_products_has_sizes_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `JbikeDH`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_has_sizes_sizes1`
    FOREIGN KEY (`sizes_id`)
    REFERENCES `JbikeDH`.`sizes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JbikeDH`.`colors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JbikeDH`.`colors` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JbikeDH`.`colorproducts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JbikeDH`.`colorproducts` (
  `products_id` INT NOT NULL,
  `colors_id` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_products_has_colors_colors1_idx` (`colors_id` ASC) VISIBLE,
  INDEX `fk_products_has_colors_products1_idx` (`products_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_products_has_colors_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `JbikeDH`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_has_colors_colors1`
    FOREIGN KEY (`colors_id`)
    REFERENCES `JbikeDH`.`colors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JbikeDH`.`generesModel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JbikeDH`.`generesModel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JbikeDH`.`genresModelproducts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JbikeDH`.`genresModelproducts` (
  `products_id` INT NOT NULL,
  `generesModel_id` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_products_has_generesModel_generesModel1_idx` (`generesModel_id` ASC) VISIBLE,
  INDEX `fk_products_has_generesModel_products1_idx` (`products_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_products_has_generesModel_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `JbikeDH`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_has_generesModel_generesModel1`
    FOREIGN KEY (`generesModel_id`)
    REFERENCES `JbikeDH`.`generesModel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JbikeDH`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JbikeDH`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NULL,
  `payment` VARCHAR(45) NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `JbikeDH`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JbikeDH`.`orderProducts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JbikeDH`.`orderProducts` (
  `orders_id` INT NOT NULL,
  `products_id` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NULL,
  `total` DECIMAL NULL,
  INDEX `fk_orders_has_products_products1_idx` (`products_id` ASC) VISIBLE,
  INDEX `fk_orders_has_products_orders1_idx` (`orders_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_orders_has_products_orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `JbikeDH`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_has_products_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `JbikeDH`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
